### ISSUE TITLE
[BUG_SP] Combine pockets broken

### ISSUE THREAD

**Issue by JDTiger** [pops64/Courseplay_FS22#19]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Start harvesting a field with a combine with CP, wait till hopper is full

**Actual behavior**
Combine will reverse to create the pocket, then end the jobs with the message finished work

**Expected behavior**
combine creates pocket and waits for unloader

**Screenshots**

**Courseplay version**
Version used: Chopper support alpha

**Comment by pops64** [comment]
I need pictures/log. Also make sure you are trying the same setup with upstream CP. None of my changes should impact pocket making

**Comment by JDTiger** [comment]
Will do later today, forgot to get the log before the first headland was done...

Worked without a hitch with the current official branch

**Comment by pops64** [comment]
Hmm, would need to see the situation and/or log

**Comment by JDTiger** [comment]
Log:
[log.txt](https://github.com/pops64/Courseplay_FS22/files/12569257/log.txt)


Video: 
https://youtu.be/qm6tcrMgN94

**Comment by pops64** [comment]
I will delve deeper into it. On first glance it should be reproducible in the official CP.  Make sure the setup is identical best way would be to reload the save and start CP in the same manner. I don't see any where the logic is breaking down. Per your log it is in the correct states and should using its logic but for some reason it is falling back to its parents logic which is to end the job when it reaches the end of the course. I will take more of a look but I don't see anything obvious or why any of my changes should effect this.

**Comment by JDTiger** [comment]
confirmed fixed, thanks
