### ISSUE TITLE
[BUG_SP] Combine Unload auger wagon broken

### ISSUE THREAD

**Issue by JDTiger** [pops64/Courseplay_FS22#20]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Harvest a field with a combine and set an auger wagon for unload

**Actual behavior**
Auger wagon instantly unfold the pipe and stays where it is

**Expected behavior**
Auger wagon keeps pipe closed and chases combine

**Courseplay version**
Version used: Chopper support Alpha

**Log**
[log.txt](https://github.com/pops64/Courseplay_FS22/files/12568264/log.txt)

**Map**
Map played on.

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by pops64** [comment]
Which augur wagon? Do you have pictures or a video? Did you attempt the same setup in official CP.  I haven't directly touched any of the unload code so this may be a problem upstream as I know auger wagons are a hit or miss in official CP

**Comment by JDTiger** [comment]
> I will take a look at it. Where you using a mod augur wagon?

Yes, used a mod wagon, will try with a base game one later.

Worked without problems when switching to the official branch

**Comment by pops64** [comment]
Ok, cause the error should reproduce in official CP as the code that broke down is identical just relocated.

**Comment by pops64** [comment]
No I see the problem now. Copy and pasting difficulties.

**Comment by pops64** [comment]
And Fixed. No version change. Will update the package release

**Comment by JDTiger** [comment]
Confirmed fixed, thanks for the quick work
