### ISSUE TITLE
[BUG_SP] "Fix for chopper targeting bug" broke auger wagons

### ISSUE THREAD

**Issue by JDTiger** [pops64/Courseplay_FS22#23]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
buy an auger wagon (for example HAWE ULW4000)

**Actual behavior**
game freezes with error

2023-09-11 23:36 Error: Running LUA method 'update'.
C:/Users/fouqu/Documents/My Games/FarmingSimulator2022/mods/Courseplay_FS22Chopper/scripts/ai/controllers/ChopperController.lua:78: attempt to call method 'getIsCpActive' (a nil value)

**Expected behavior**
Buying an auger weagon works

**Screenshots**

**Courseplay version**
Version used: current Chopper support branch

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

[log.txt](https://github.com/pops64/Courseplay_FS22/files/12580633/log.txt)

**Map**
Map played on.

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by pops64** [comment]
I just pushed a fix try it out. Logic say you should have gotten the error.

**Comment by JDTiger** [comment]
Checked fixed

thanks for your quick work on those little bugs
