### ISSUE TITLE
[BUG_SP] AI worker %s has stopped work unexpectedly - left the course! (maybe base version bug)

### ISSUE THREAD

**Issue by JDTiger** [pops64/Courseplay_FS22#24]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
harvest a field with long straights from chopper to targetpoint

**Actual behavior**
When full, the course from the chopper to the target point get generated with a long straight without waypoints, causing CP to turn off with the message left the course.

**Expected behavior**
Course gets generated with waypoints close enough together for CP to work

**Screenshots**
https://youtu.be/TRzmnY_HZh8

**Courseplay version**
Version used:  Current Chopper support fork

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.
[log.txt](https://github.com/pops64/Courseplay_FS22/files/12585259/log.txt)
relevant lines are 2790 to 2910

**Map**
Map played on.

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by pops64** [comment]
Case of garbage in garbage out should be fixed
