### ISSUE TITLE
[BUG_SP] Sharp Headlands Don't Work Well

### ISSUE THREAD

**Issue by pops64** [pops64/Courseplay_FS22#3]
Currently sharp headland turns don't work well as the logic isn't programmed in. It should be fine with wider work widths as the unload drive does stay out of the way of the chopper but if there isn't enough space generated pathfinder will break down

**Comment by pops64** [comment]
After more testing. On the 2nd or higher headland this does cause issues. The unload driver is to close for pathfinder to call. Need to figure out a good solution to this. Unfortunately driving off the field probably will be necessary because the chopper takes up all the space.

**Comment by pops64** [comment]
Alright sharp headland turns are working in the last. Please test them out for now I won't package a release. So you will have to manually package if you know how if not I will package it later once I do some more testing my self.

I may make a course to handle the turn right now it is dumb and just drives to the next way point so it may cut the corner

**Comment by regs1980** [comment]
Chopper does not work the corner with pocket function.
As a result, the driver does not find a way to the overload point.

https://drive.google.com/file/d/1y5OTQEYdGxaUWbAOMO6FnnBVS11pZan1/view?usp=drive_link

**Comment by pops64** [comment]
Try again. Was half asleep when I made my last push of the night. Things that were untested got sent out sorry :(

**Comment by regs1980** [comment]
Looks very good already.
Still fix this bug, then the base is there.  

https://github.com/pops64/Courseplay_FS22/issues/5#issuecomment-1716408434

**Comment by pops64** [comment]
For now you can force it to go home which would cause it to call the next one which make the chopper move when it shows up solving the problem. You may have to hit twice once to call the unloader and again once the combine is clear.(Upstream CP put this on a timer instead on task completion ...) Picture for those that do know
![20230912204412_1](https://github.com/pops64/Courseplay_FS22/assets/10678220/27c43f3c-ada1-4362-a617-9a8f5616770f)

**Comment by pops64** [comment]
Not fixed but not a problem any more. TODO look at fixing the combine turn so it ends where the fruit is not so far back which is what is causing this issue. The chopper doesn't look for trailers in range that is front of the pipe

**Comment by pops64** [comment]
Closed fixed in 7.3.0.6 release. Please post any new issues if you have them

**Comment by regs1980** [comment]
Look at the video, some things are already very well solved, others are not.
Driver must drive further back to be able to calculate the overload point correctly in the second headland.  
LUA error on the last piece.

https://drive.google.com/file/d/18-nBWx0xyY-1Wcef74Pmi-5OHJKT08Ku/view?usp=drive_link

**Comment by pops64** [comment]
Any new bugs regarding sharp turn support please open a new issue. I will still take a look. Its a problem with the chopper hanging out so far back after finishing the turn
