### ISSUE TITLE
[Feature] Switch from chase mode to drive beside when switching to 2nd headland

### ISSUE THREAD

**Issue by pops64** [pops64/Courseplay_FS22#5]
May be possible to switch from chase mode on the first headland drive beside

**Comment by regs1980** [comment]
Driver must drive beside the chopper when it is in the second headland.
Driver can not make the calculation and find the way to the overload point.

https://drive.google.com/file/d/1aCbRTZGLchU2_ZUFQT5dc3P8dMiN2cib/view?usp=drive_link

**Comment by pops64** [comment]
That is a sharp turn problem belongs in that issue. Otherwise staying behind the chopper doesn't effect anything other than calling next unloader won't occur until the one unloading behind the chopper goes home

**Comment by pops64** [comment]
For now this is has only been pushed. I will package it later today I want to make sure that nothing else is broken

**Comment by pops64** [comment]
Closed fixed in 7.3.0.6 release. Please post any new issues if you have them
